version: "3.9"

volumes:
  contosoads-data:

services:
  db:
    image: postgres:${POSTGRES_TAG:-14-alpine}
    ports:
      - "5432:5432"
    volumes:
      - contosoads-data:/var/lib/postgresql/data
      - ./deploy/migrate.sql:/docker-entrypoint-initdb.d/1-migrate.sql
    environment:
      - POSTGRES_PASSWORD=pass@word1
      - POSTGRES_DB=contosoads
