CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Ads" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Price" integer NOT NULL,
    "Description" character varying(1000),
    "ImageUri" character varying(1000),
    "ThumbnailUri" character varying(1000),
    "PostedDate" timestamp with time zone NOT NULL,
    "Category" integer NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_Ads" PRIMARY KEY ("Id")
);

CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220317174057_Initial', '8.0.16');

COMMIT;

START TRANSACTION;

DROP TABLE "DataProtectionKeys";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250517125008_RemoveDataProtection', '8.0.16');

COMMIT;

