apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: imageprocessor-storage
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: storageAccount
      secretKeyRef:
        name: storageAccount
    - name: storageAccessKey
      secretKeyRef:
        name: storageAccountKey
    - name: container
      value: "images"
    - name: decodeBase64
      value: true
#   When running the application with Docker Compose, comment the next two lines.
    - name: endpoint
      value: "https://127.0.0.1:10000"
#   When running the application with Docker Compose, uncomment the next two lines 
#    - name: endpoint
#      value: "http://host.docker.internal:10000"
auth:
  secretStore: dev-secrets
scopes:
  - contosoads-imageprocessor