apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: thumbnail-request-receiver
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
    - name: storageAccount
      secretKeyRef:
        name: storageAccount
    - name: storageAccessKey
      secretKeyRef:
        name: storageAccountKey
    - name: queue
      value: "thumbnail-request"
    - name: route
      value: "/thumbnail-request"
#   When running the application and Dapr locally, uncomment the next two lines to point Dapr to its Azure Storage Blob endpoint.
#    - name: endpoint
#      value: "http://127.0.0.1:10001"
#   When running the entire software stack in Docker, uncomment the next two lines.
#    - name: endpoint
#      value: "http://host.docker.internal:10001"
auth:
  secretStore: dev-secrets
scopes:
  - contosoads-imageprocessor