name: Deploy ContosoAds to Azure Container Apps across multiple regions
concurrency: contosoads-deploy-${{ github.ref }}

on:
  workflow_dispatch:

env:
    DB_LOGIN: contosoads
    REPOSITORY: 'https://github.com/joergjo/contosoads-containerapp.git'

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        include:
          - location: westeurope
            code: weu
          - location: northeurope
            code: neu
#          - location: uksouth
#            code: uks
#          - location: francecentral
#            code: frc
#          - location: norwayeast
#            code: noe
#          - location: eastus
#            code: eus
          - location: centralus
            code: cus
          - location: canadacentral
            code: cac
#          - location: eastasia
#            code: eaa
#          - location: australiaeast
#            code: aue
#          - location: japaneast
#            code: jpe
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN }}

      - name: Create resource groups
        uses: azure/CLI@v1
        with:
          inlineScript: >
            echo "Creating resource group"
            echo "Executing 'az group create -l ${{ matrix.location }} -n contosoads-test-${{ matrix.code }}'"            
            az group create -l ${{ matrix.location }} -n contosoads-test-${{ matrix.code }}

      - name: Deploy Bicep template  
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: contosoads-test-${{ matrix.code }}
          template: ./deploy/main.bicep
          parameters: baseName=contosoads${{ matrix.code }} postgresLogin=${{ env.DB_LOGIN }} postgresLoginPassword=${{ secrets.DB_PWD }} repository=${{ env.REPOSITORY }}

      - name: Log success
        run: 
          - echo '${{ matrix.location }}: 🟢' >> $GITHUB_STEP_SUMMARY
        if: ${{ steps.id.outcome == 'success' }}
      - name: Log failure
        run:
          - echo '${{ matrix.location }}: 🔴' >> $GITHUB_STEP_SUMMARY
        if: ${{ steps.id.outcome == 'failure' }}

      - name: Delete resource groups
        uses: azure/CLI@v1
        with:
          inlineScript: >
            echo "Deleting resource group"
            echo "Executing 'az group delete -n contosoads-test-${{ matrix.code }} -y'"            
            az group delete -n contosoads-test-${{ matrix.code }} -y
