name: ContosoAds deployment stress test
concurrency: contosoads-deploy-${{ github.ref }}

on:
  workflow_dispatch:

env:
    DB_LOGIN: contosoads
    REPOSITORY: 'https://github.com/joergjo/contosoads-containerapp.git'

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        include:
          - location: westeurope
            code: weu
#          - location: northeurope
#            code: neu
          - location: uksouth
            code: uks
#          - location: francecentral
#            code: frc
#          - location: germanywestcentral
#            code: gew
#          - location: norwayeast
#            code: noe
#          - location: eastus
#            code: eus
          - location: eastus2
            code: eus2
#          - location: centralus
#            code: cus
#          - location: southcentralus
#            code: scus
#          - location: northcentralus
#            code: ncus
          - location: westus
            code: wus
#          - location: westus3
#            code: wus3
#          - location: canadacentral
#            code: cac
          - location: eastasia
            code: eaa
          - location: australiaeast
            code: aue
#          - location: japaneast
#            code: jpe
#          - location: koreacentral
#            code: koc
#          - location: brazilsouth
#            code: brs
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN }}

      - name: Create resource groups
        uses: azure/CLI@v1
        id: create-rg
        with:
          inlineScript: >
            echo "Creating resource group"
            
            echo "Executing 'az group create -l ${{ matrix.location }} -n contosoads-test-${{ matrix.code }}'"    

            az group create -l ${{ matrix.location }} -n contosoads-test-${{ matrix.code }}

      - name: Deploy Bicep template  
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          deploymentName: contosoads-${{ github.run_number }}-${{ github.run_attempt }}
          resourceGroupName: contosoads-test-${{ matrix.code }}
          template: ./deploy/main.bicep
          parameters: baseName=contosoads${{ matrix.code }} postgresLogin=${{ env.DB_LOGIN }} postgresLoginPassword=${{ secrets.DB_PWD }} repository=${{ env.REPOSITORY }}

      - name: Log success
        run: |
          echo '${{ matrix.location }}: :white_check_mark:' >> $GITHUB_STEP_SUMMARY
        if: ${{ always() && steps.deploy.outcome == 'success' }}
      - name: Log failure
        run: |
          echo '${{ matrix.location }}: :x:' >> $GITHUB_STEP_SUMMARY
        if: ${{ always() && steps.deploy.outcome == 'failure' }}

      - name: Delete resource groups
        uses: azure/CLI@v1
        with:
          inlineScript: >
            echo "Deleting resource group"

            echo "Executing 'az group delete -n contosoads-test-${{ matrix.code }} -y'" 

            az group delete -n contosoads-test-${{ matrix.code }} -y
        if: ${{ always() && steps.create-rg.outcome == 'success' }}